<?php 
return [
    [
        "name"=> "Casa vacanze di Luca",
        "slug"=> "casa-vacanze-di-Luca",
        "price"=> 75,
        "description"=> "Confortevole monolocale, piccolo piccolo",
        "rooms"=> 2,
        "max_people"=> 2,
        "bathrooms"=> 1,
        "square_meters"=> 20,
        "address"=> "Via Roma, 14 Gambolò",
        "image"=> null,
        "visibility"=> 1,
    ],
    [
        "name"=> "Loft in centro",
        "slug"=> "loft-in-centro",
        "price"=> 95,
        "description"=> "Loft di classe",
        "rooms"=> 3,
        "max_people"=> 2,
        "bathrooms"=> 1,
        "square_meters"=> 23,
        "address" => "Viale Indipendeza, 54 Milano",
        "image"=> null,
        "visibility"=> 1,
    ],
    [
        "name"=> "Casa sull'albero",
        "slug"=> "casa-sull-albero",
        "price"=> 66,
        "description"=> "Splendida casetta sull'albero",
        "rooms"=> 1,
        "max_people"=> 2,
        "bathrooms"=> 1,
        "square_meters"=> 15,
        "address" => "Corso Como, 11 Milano",
        "image"=> null,
        "visibility"=> 1,
    ],
];