<?php 
return [
    [
        "name"=> "Casa vacanze di Luca",
        "slug"=> "casa-vacanze-di-Luca",
        "price"=> 75,
        "description"=> "Confortevole monolocale, piccolo piccolo",
        "rooms"=> 2,
        "max_people"=> 2,
        "bathrooms"=> 1,
        "square_meters"=> 20,
        "latitude"=> 45.2649,
        "longitude"=> 8.85869,
        "image"=> null,
        "visibility"=> 1,
    ],
    [
        "name"=> "Loft in centro",
        "slug"=> "loft-in-centro",
        "price"=> 95,
        "description"=> "Loft di classe",
        "rooms"=> 3,
        "max_people"=> 2,
        "bathrooms"=> 1,
        "square_meters"=> 23,
        "latitude"=> 41.162532,
        "longitude"=> 16.245832,
        "image"=> null,
        "visibility"=> 1,
    ],
    [
        "name"=> "Casa sull'albero",
        "slug"=> "casa-sull-albero",
        "price"=> 66,
        "description"=> "Splendida casetta sull'albero",
        "rooms"=> 1,
        "max_people"=> 2,
        "bathrooms"=> 1,
        "square_meters"=> 15,
        "latitude"=> 43.162542,
        "longitude"=> 17.245732,
        "image"=> null,
        "visibility"=> 1,
    ],
];