<?php 
return [
    [
        "name"=> "Casa vacanze di Luca",
        "slug"=> "casa-vacanze-di-Luca",
        "price"=> 75,
        "description"=> "Confortevole monolocale, piccolo piccolo",
        "rooms"=> 2,
        "max_people"=> 2,
        "bathrooms"=> 1,
        "square_meters"=> 20,
        "latitude"=> 45.2649,
        "longitude"=> 8.85869,
        "image"=> "https://images-ext-2.discordapp.net/external/UCOCm1fZjzakO90Y8SNuQMn-JoURRk6PVke396jVo74/%3Fq%3Dtbn%3AANd9GcQhB7zlYQvckAf9dsIrW1xmN1T8dxL4GcVvGo5E7Dx8BTH203vsoyxoy5p48-LEUfn4jT0%26usqp%3DCAU/https/encrypted-tbn0.gstatic.com/images",
        "visibility"=> 1,
    ],
    [
        "name"=> "Loft in centro",
        "slug"=> "loft-in-centro",
        "price"=> 95,
        "description"=> "Loft di classe",
        "rooms"=> 3,
        "max_people"=> 2,
        "bathrooms"=> 1,
        "square_meters"=> 23,
        "latitude"=> 41.162532,
        "longitude"=> 16.245832,
        "image"=> "https://images-ext-2.discordapp.net/external/UCOCm1fZjzakO90Y8SNuQMn-JoURRk6PVke396jVo74/%3Fq%3Dtbn%3AANd9GcQhB7zlYQvckAf9dsIrW1xmN1T8dxL4GcVvGo5E7Dx8BTH203vsoyxoy5p48-LEUfn4jT0%26usqp%3DCAU/https/encrypted-tbn0.gstatic.com/images",
        "visibility"=> 1,
    ],
    [
        "name"=> "Casa sull'albero",
        "slug"=> "casa-sull-albero",
        "price"=> 66,
        "description"=> "Splendida casetta sull'albero",
        "rooms"=> 1,
        "max_people"=> 2,
        "bathrooms"=> 1,
        "square_meters"=> 15,
        "latitude"=> 43.162542,
        "longitude"=> 17.245732,
        "image"=> "https://images-ext-2.discordapp.net/external/UCOCm1fZjzakO90Y8SNuQMn-JoURRk6PVke396jVo74/%3Fq%3Dtbn%3AANd9GcQhB7zlYQvckAf9dsIrW1xmN1T8dxL4GcVvGo5E7Dx8BTH203vsoyxoy5p48-LEUfn4jT0%26usqp%3DCAU/https/encrypted-tbn0.gstatic.com/images",
        "visibility"=> 1,
    ],
];